# Generated by Django 3.1 on 2020-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('born', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('batting', models.CharField(max_length=200)),
                ('bowling', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('teams', models.CharField(max_length=200)),
                ('field_position', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('man_of_the_matchs', models.CharField(max_length=200)),
            ],
        ),
    ]
