# Generated by Django 3.1 on 2020-08-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internationalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_side', models.CharField(max_length=200)),
                ('test_debut', models.CharField(max_length=200)),
                ('last_test', models.CharField(max_length=200)),
                ('ODI_debut', models.CharField(max_length=200)),
                ('last_ODI', models.CharField(max_length=200)),
                ('ODI_shirtno', models.CharField(max_length=200)),
                ('T20I_debut', models.CharField(max_length=200)),
                ('last_T20I', models.CharField(max_length=200)),
                ('T20I_shirtno', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international', to='base.personalinfo')),
            ],
        ),
    ]
