# Generated by Django 3.1 on 2020-08-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_internationalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic', to='base.personalinfo')),
            ],
        ),
    ]
