# Generated by Django 3.1 on 2020-08-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_careerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestperformances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('desc', models.TextField(default='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestp', to='base.personalinfo')),
            ],
        ),
    ]
