# Generated by Django 3.1 on 2020-08-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestperformances',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestperformances', to='base.personalinfo'),
        ),
        migrations.AlterField(
            model_name='records',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internationalrecords', to='base.personalinfo'),
        ),
        migrations.CreateModel(
            name='BatFiledaverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('Mat', models.CharField(max_length=200)),
                ('Inns', models.CharField(max_length=200)),
                ('NO', models.CharField(max_length=200)),
                ('Runs', models.CharField(max_length=200)),
                ('HS', models.CharField(max_length=200)),
                ('Ave', models.CharField(max_length=200)),
                ('BF', models.CharField(max_length=200)),
                ('SR', models.CharField(max_length=200)),
                ('_100', models.CharField(max_length=200)),
                ('_50', models.CharField(max_length=200)),
                ('_4s', models.CharField(max_length=200)),
                ('_6s', models.CharField(max_length=200)),
                ('Ct', models.CharField(max_length=200)),
                ('St', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Battingandfieldingaverages', to='base.personalinfo')),
            ],
        ),
    ]
