# Generated by Django 3.1 on 2020-08-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200822_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowlingaverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('Mat', models.CharField(max_length=200)),
                ('Inns', models.CharField(max_length=200)),
                ('Balls', models.CharField(max_length=200)),
                ('Runs', models.CharField(max_length=200)),
                ('Wkts', models.CharField(max_length=200)),
                ('BBI', models.CharField(max_length=200)),
                ('BBM', models.CharField(max_length=200)),
                ('Ave', models.CharField(max_length=200)),
                ('Econ', models.CharField(max_length=200)),
                ('SR', models.CharField(max_length=200)),
                ('_4w', models.CharField(max_length=200)),
                ('_5w', models.CharField(max_length=200)),
                ('_10', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bowlingaverages', to='base.personalinfo')),
            ],
        ),
    ]
