# Generated by Django 3.1 on 2020-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_awards_nationalhonours'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='awardname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
