# Generated by Django 3.1 on 2020-08-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200822_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideCricketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Outsidecricket', to='base.personalinfo')),
            ],
        ),
    ]
