# Generated by Django 3.1 on 2020-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_career_careerindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerindex',
            name='desc',
            field=models.TextField(),
        ),
    ]
