# Generated by Django 3.1 on 2020-08-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200823_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplscoresmodel',
            name='wc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msdiplscore', to='base.iplscoremodel'),
        ),
    ]
