# Generated by Django 3.1 on 2020-08-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20200823_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplscoremodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inIPL', to='base.personalinfo'),
        ),
        migrations.CreateModel(
            name='Recentmatchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recentmatchs', to='base.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Recentmatchdecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batting', models.CharField(max_length=200)),
                ('Bowling', models.CharField(max_length=200)),
                ('Opposition', models.CharField(max_length=200)),
                ('Match_date', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recentm', to='base.recentmatchs')),
            ],
        ),
    ]
