# Generated by Django 3.1 on 2020-08-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200823_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirment', to='base.personalinfo')),
            ],
        ),
    ]
