# Generated by Django 3.1 on 2020-08-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_retirment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement', to='base.personalinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Retirment',
        ),
    ]
