from django.contrib import admin
from .models import Reference,Recentmatchdecs,Recentmatchs,Retirement,iplscoremodel,iplscoresmodel,worldcupscore,wcscores,Hascaptain,worldcup,IPL,Personalinfo,Internationalinfo,DomesticInfo,Careerstats,Bestperformances,records,BatFiledaverages,Bowlingaverages,Timeline,Awards,honours,OutsideCricketModel,background,careerindex,Career
admin.site.register(Personalinfo)
admin.site.register(Internationalinfo)
admin.site.register(DomesticInfo)
admin.site.register(Careerstats)
admin.site.register(Bestperformances)
admin.site.register(records)
admin.site.register(BatFiledaverages)
admin.site.register(Bowlingaverages)
admin.site.register(Timeline)
admin.site.register(Awards)
admin.site.register(honours)
admin.site.register(OutsideCricketModel)
admin.site.register(background)
admin.site.register(careerindex)
admin.site.register(Career)
admin.site.register(Hascaptain)
admin.site.register(worldcup)
admin.site.register(IPL)
admin.site.register(worldcupscore)
admin.site.register(wcscores)
admin.site.register(iplscoremodel)
admin.site.register(iplscoresmodel)
admin.site.register(Recentmatchdecs)
admin.site.register(Recentmatchs)
admin.site.register(Retirement)
admin.site.register(Reference)